sonar.projectKey=unowebsim
sonar.projectName=UnoWebSim
sonar.projectVersion=1.0
sonar.plugins.downloadOnlyRequired=false

# Diese Konfigs funktionieren nicht:
#sonar.sources.1=client/src
#sonar.sources.2=server
#sonar.sources.3=shared
#sonar.sources=client/src,server

sonar.sources=client/src,shared,server

sonar.tests=tests
sonar.exclusions=server/arduino-cache/**,**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
